### ISSUE TITLE
Last emote in chat appears giant in the background 

### ISSUE THREAD

**Issue by Onijima** [IS2511/ChatIS#11]
![image](https://user-images.githubusercontent.com/90558278/229301111-71ad6c57-3a68-4daf-b98e-77dce1d17cb5.png)

**Comment by IS2511** [comment]
April 1st easter egg. :tada: I suggest you just enjoy it, but if you really really want to disable it, change date on your PC to something other than April 1st.

**Comment by Onijima** [comment]
Hahaha 🤣 you got me

**Comment by JCog** [comment]
I know you didn't mean any harm by this and you're probably just going to roll your eyes at me and call me a buzzkill, but please don't do anything like this in the future. I just spent a bunch of time trying to figure out what I thought was a bug, delaying my stream. And now that I know what it is, the only way to turn it off is to change the date which breaks multiple other things I have running on my computer.

Please at least include an actual off switch next time.

**Comment by IS2511** [comment]
This is disabled until I implement #35. My apologies to people who were negatively affected by this.
