### ISSUE TITLE
Suggestion for better text shadow

### ISSUE THREAD

**Issue by Johnnycyan** [IS2511/ChatIS#12]
Instead of using text-shadow you can just use `filter: drop-shadow(1px 1px 2px #333);` on the `#chat_container` and it supports drop-shadow for 7tv paint names and also emotes which are both impossible with the text-shadow css currently used.

So essentially I recommend changing from using text-shadow settings to using the drop-shadow filter instead for better support.

**Comment by IS2511** [comment]
Implemented :heavy_check_mark:
