### ISSUE TITLE
[Feature Request] Allow showing bot commands

### ISSUE THREAD

**Issue by jprjr** [IS2511/ChatIS#20]
By default, user's bot commands are hidden, I'd like to be able to show them (messages beginning with commands like `!info`). Thank you!

**Comment by IS2511** [comment]
Bot commands are hidden only when bots are hidden, it's all tied to the "show bots" setting. I do think that it should've been communicated more clearly, so I'll rename the setting.

If you want showing bots and showing commands as separate settings please open a new issue.
