### ISSUE TITLE
[Suggestion] multi-platform chatbox using Streamer.Bot

### ISSUE THREAD

**Issue by ofenixgamer** [IS2511/ChatIS#30]
Using a tool called Streamer.Bot, it's possible to do a lot of things related to streaming, including widgets like chatboxes. With this, you can create a multi-platform chatbox that work with Twitch, YouTube, and Trovo!! Here are some chatboxes made with Streamer.Bot: https://github.com/izzy/stream-chat and https://github.com/BlackyWhoElse/streamer.bot-actions/tree/main/widget/chat

**Comment by IS2511** [comment]
This looks like spam.

**Comment by ofenixgamer** [comment]
Why? I was just making a suggestion to improve your chat because I would also like it to work with YouTube. and I thought Streamer.Bot could be helpful for that.

**Comment by IS2511** [comment]
Sorry if you are a real person, your message looked too \#ad.

If this suggestion is real, it's pretty weird still. I'm not going to require users of this overlay to download and install a separate program. The whole idea of this overlay is not needing any 3rd party apps on your computer, just an OBS browser source.

Optional Streamer.bot integration on the other hand... Might be something worth looking at. But definitely out of scope for this issue, make a new one if you want that, maybe with some ideas on what to use it for. I'm currently pretty busy and integrating with Streamer.bot would probably be pretty low on my TODO list, sorry.

**Comment by ofenixgamer** [comment]
No problem, the first message really wasn't very good. I'm going to make a new issue, can you delete this one?
