### ISSUE TITLE
YouTube chat support

### ISSUE THREAD

**Issue by IS2511** [IS2511/ChatIS#34]
Eventually :tm:

**Comment by Linaryx** [comment]
Это можно считать началом работы над поддержкой чата Ютуба?

**Comment by IS2511** [comment]
No, I haven't started yet. Don't expect it any time soon. But it is planned...

---

Нет, я еще не начинал. Скоро не ждите. Но в планах числится...

**Comment by IS2511** [comment]
I just realized this is a duplicate of #25... Why did I create this? Closed in favor of #25.
